# Generated by Django 3.2.13 on 2022-05-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Documents Template', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Docs_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Documents Template', max_length=250)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.category')),
            ],
        ),
    ]
