# Generated by Django 3.2.13 on 2022-05-21 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectJenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Documents Template', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TempSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='section', max_length=250)),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dokumen.sectjenis')),
            ],
        ),
    ]
