# Generated by Django 3.2.13 on 2022-05-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0002_sectjenis_tempsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsection',
            name='isi',
            field=models.TextField(default=''),
        ),
    ]
