# Generated by Django 3.2.13 on 2022-05-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0003_tempsection_isi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempsection',
            name='isi',
        ),
        migrations.AddField(
            model_name='tempsection',
            name='tempName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dokumen.docs_template'),
            preserve_default=False,
        ),
    ]
