# Generated by Django 3.2.13 on 2023-01-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0004_auto_20220521_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Documents Template', max_length=250)),
                ('keterangan', models.CharField(default='-', max_length=250)),
                ('status_dokumen', models.CharField(choices=[('0', 'Tidak Aktif'), ('1', 'Aktif'), ('2', 'Dalam Proses'), ('3', 'Selesai'), ('4', 'Batal')], default=0, max_length=2)),
            ],
        ),
    ]
