# Generated by Django 3.2.13 on 2023-03-03 12:46

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tugasan', '0003_auto_20230302_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tugasan',
            name='kumpulan',
        ),
        migrations.RemoveField(
            model_name='tugasan',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tugasan',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='tugasan',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tugasan',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='tugasan',
            name='tree_id',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tugasan.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tugasan',
            name='kategori',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tugasan.category'),
        ),
    ]
