# Generated by Django 2.1.2 on 2018-11-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_profile_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jantina',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='noahli',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='nokp',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='st_ahli',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='st_belajar',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='st_bwg',
            field=models.CharField(default='Putih', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefon',
            field=models.CharField(default='', max_length=21),
        ),
    ]
