# Generated by Django 2.1.2 on 2018-11-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0004_auto_20181113_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jantina',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kelas',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='noahli',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='st_ahli',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='st_belajar',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='st_jurulatih',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=21),
        ),
    ]
